## https://www.appveyor.com/docs/appveyor-yml/
#image: Visual Studio 2022
image: Ubuntu2004
version: 1.0.{build}

configuration:
- Debug

platform: Any CPU

pull_requests:  
  do_not_increment_build_number: true

environment:
  # Don't report back to the mothership
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOCKER_USER: corts
  DOCKER_PASS:
    secure: 0rxw6OrmXRqB3UuBZFbC/w==
  SONAR_TOKEN:
    secure: iMwieUAbbS4oTgEVtdGWUujzaBkeNjhFzsPMj8Y3c8vkjWyCN2miKlyfWA25jtBr
  CONFIGURATION: Debug

init:
- ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")
- ps: $env:DOCKER_PASS | docker login --username $env:DOCKER_USER --password-stdin
- docker version

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

before_build:
- set DNX_BUILD_VERSION=%APPVEYOR_BUILD_NUMBER%
- dotnet --info

build:
  verbosity: minimal

build_script:
- ps: >-
    $buildNumber = $env:APPVEYOR_BUILD_NUMBER;
    $branch = $env:APPVEYOR_REPO_BRANCH;
    if (Test-Path env:APPVEYOR_PULL_REQUEST_NUMBER) {
      $branch = $Env:APPVEYOR_PULL_REQUEST_HEAD_REPO_BRANCH;
      $target = $Env:APPVEYOR_REPO_BRANCH;
      $commit = $Env:APPVEYOR_PULL_REQUEST_HEAD_COMMIT;
      .\build-dockerimages.ps1 -branch $branch -buildCounter $buildNumber -pushImage:$false -pullRequestId $env:APPVEYOR_PULL_REQUEST_NUMBER -target $target -commit $commit;

    } else {
      .\build-dockerimages.ps1 -branch $branch -buildCounter $buildNumber -pushImage:$true;
    }
    $fileVersion = $env:APPVEYOR_BUILD_VERSION;

cache:
- '%USERPROFILE%\.nuget\packages'
  
nuget:
  disable_publish_on_pr: true
 
